
export const FIRST_INCREMENT_COUNTER = 'FIRST_INCREMENT_COUNTER'
export const FIRST_ASSIGN_ID = 'FIRST_ASSIGN_ID'
export const SET_TOKEN = 'SET_TOKEN'


export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'

export const GEO_LOCATION_SUCCESS = 'GEO_LOCATION_SUCCESS'
export const GEO_LOCATION_FAILURE = 'GEO_LOCATION_FAILURE'
export const GEO_LASTCENTER_UPDATE = 'GEO_LASTCENTER_UPDATE'
